modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="nine_armory"
version="1.0.0"
displayName="9ine's Armory"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="gamer, MCreator"

[[dependencies.nine_armory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




